
// Code generated by MetaFFI. DO NOT EDIT.
// Host code for py_extractor.json
package py_extractor

import (
	"github.com/MetaFFI/lang-plugin-go/api"
	"github.com/MetaFFI/plugin-sdk/compiler/go/IDL"
	. "github.com/MetaFFI/lang-plugin-go/go-runtime"
)





var runtime *api.MetaFFIRuntime
var mod *api.MetaFFIModule

// Entities Callers








var variable_info_get_name_caller func(...interface{}) ([]interface{}, error)


var variable_info_get_type_caller func(...interface{}) ([]interface{}, error)


var variable_info_get_is_getter_caller func(...interface{}) ([]interface{}, error)


var variable_info_get_is_setter_caller func(...interface{}) ([]interface{}, error)





var variable_info_Releasevariable_info_caller func(...interface{}) ([]interface{}, error)



var parameter_info_get_name_caller func(...interface{}) ([]interface{}, error)


var parameter_info_get_type_caller func(...interface{}) ([]interface{}, error)


var parameter_info_get_is_default_value_caller func(...interface{}) ([]interface{}, error)


var parameter_info_get_is_optional_caller func(...interface{}) ([]interface{}, error)


var parameter_info_get_kind_caller func(...interface{}) ([]interface{}, error)





var parameter_info_Releaseparameter_info_caller func(...interface{}) ([]interface{}, error)



var function_info_get_name_caller func(...interface{}) ([]interface{}, error)


var function_info_get_comment_caller func(...interface{}) ([]interface{}, error)


var function_info_get_parameters_caller func(...interface{}) ([]interface{}, error)


var function_info_get_return_values_caller func(...interface{}) ([]interface{}, error)





var function_info_Releasefunction_info_caller func(...interface{}) ([]interface{}, error)



var class_info_get_name_caller func(...interface{}) ([]interface{}, error)


var class_info_get_comment_caller func(...interface{}) ([]interface{}, error)


var class_info_get_fields_caller func(...interface{}) ([]interface{}, error)


var class_info_get_methods_caller func(...interface{}) ([]interface{}, error)





var class_info_Releaseclass_info_caller func(...interface{}) ([]interface{}, error)



var py_info_get_globals_caller func(...interface{}) ([]interface{}, error)


var py_info_get_functions_caller func(...interface{}) ([]interface{}, error)


var py_info_get_classes_caller func(...interface{}) ([]interface{}, error)





var py_info_Releasepy_info_caller func(...interface{}) ([]interface{}, error)




var py_extractor_extract_caller func(...interface{}) ([]interface{}, error)


var py_extractor_py_extractor_caller func(...interface{}) ([]interface{}, error)


var py_extractor_Releasepy_extractor_caller func(...interface{}) ([]interface{}, error)




func BindModuleToCode(modulePath string){
	runtime = api.NewMetaFFIRuntime("python3")
	err := runtime.LoadRuntimePlugin()
	if err != nil {
		panic(err)
	}

	mod, err = runtime.LoadModule(modulePath)
	if err != nil {
		panic(err)
	}

	// load functions
	loadFF := func(fpath string, params []IDL.MetaFFITypeInfo, retvals []IDL.MetaFFITypeInfo) (caller func(...interface{}) ([]interface{}, error)){
		var err error
		caller, err = mod.LoadWithInfo(fpath, params, retvals)
		if err != nil{ // failed
			panic(err)
		}
		return caller
	}

	
	
	
	
	

	
	
	variable_info_get_name_caller = loadFF("entrypoint_function=EntryPoint_variable_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	variable_info_get_type_caller = loadFF("entrypoint_function=EntryPoint_variable_info_get_type,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	variable_info_get_is_getter_caller = loadFF("entrypoint_function=EntryPoint_variable_info_get_is_getter,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	variable_info_get_is_setter_caller = loadFF("entrypoint_function=EntryPoint_variable_info_get_is_setter,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	
	
	
	
	parameter_info_get_name_caller = loadFF("entrypoint_function=EntryPoint_parameter_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	parameter_info_get_type_caller = loadFF("entrypoint_function=EntryPoint_parameter_info_get_type,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	parameter_info_get_is_default_value_caller = loadFF("entrypoint_function=EntryPoint_parameter_info_get_is_default_value,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	parameter_info_get_is_optional_caller = loadFF("entrypoint_function=EntryPoint_parameter_info_get_is_optional,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	parameter_info_get_kind_caller = loadFF("entrypoint_function=EntryPoint_parameter_info_get_kind,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	
	
	
	
	function_info_get_name_caller = loadFF("entrypoint_function=EntryPoint_function_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	function_info_get_comment_caller = loadFF("entrypoint_function=EntryPoint_function_info_get_comment,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	function_info_get_parameters_caller = loadFF("entrypoint_function=EntryPoint_function_info_get_parameters,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE_ARRAY, Alias: "parameter_info", Type: 98304, Dimensions: 0 },})
	
	
	function_info_get_return_values_caller = loadFF("entrypoint_function=EntryPoint_function_info_get_return_values,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8_ARRAY, Alias: "", Type: 69632, Dimensions: 0 },})
	
	
	
	
	
	
	class_info_get_name_caller = loadFF("entrypoint_function=EntryPoint_class_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	class_info_get_comment_caller = loadFF("entrypoint_function=EntryPoint_class_info_get_comment,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	class_info_get_fields_caller = loadFF("entrypoint_function=EntryPoint_class_info_get_fields,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE_ARRAY, Alias: "variable_info", Type: 98304, Dimensions: 0 },})
	
	
	class_info_get_methods_caller = loadFF("entrypoint_function=EntryPoint_class_info_get_methods,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE_ARRAY, Alias: "function_info", Type: 98304, Dimensions: 0 },})
	
	
	
	
	
	
	py_info_get_globals_caller = loadFF("entrypoint_function=EntryPoint_py_info_get_globals,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE_ARRAY, Alias: "variable_info", Type: 98304, Dimensions: 0 },})
	
	
	py_info_get_functions_caller = loadFF("entrypoint_function=EntryPoint_py_info_get_functions,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE_ARRAY, Alias: "function_info", Type: 98304, Dimensions: 0 },})
	
	
	py_info_get_classes_caller = loadFF("entrypoint_function=EntryPoint_py_info_get_classes,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE_ARRAY, Alias: "class_info", Type: 98304, Dimensions: 0 },})
	
	
	
	
	
	
	
	py_extractor_extract_caller = loadFF("entrypoint_class=py_extractor,entrypoint_function=EntryPoint_py_extractor_extract,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "py_info", Type: 32768, Dimensions: 0 },})
	
	
	py_extractor_py_extractor_caller = loadFF("entrypoint_function=EntryPoint_py_extractor_py_extractor,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },})
	
	
	
}

func Free() error{
	return runtime.ReleaseRuntimePlugin()
}






// Code to call foreign functions in module py_extractor via XLLR



type Variable_Info struct{
	h Handle
}



func (this *Variable_Info) GetHandle() Handle{
	return this.h
}

func (this *Variable_Info) SetHandle(h Handle){
	this.h = h
}



func (this *Variable_Info) Get_Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = variable_info_get_name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Variable_Info) Get_Type_Getter() (type__ string, err error){
	

	var res []interface{}
	
	res, err = variable_info_get_type_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Variable_Info) Get_Is_Getter_Getter() (is_getter bool, err error){
	

	var res []interface{}
	
	res, err = variable_info_get_is_getter_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}




func (this *Variable_Info) Get_Is_Setter_Getter() (is_setter bool, err error){
	

	var res []interface{}
	
	res, err = variable_info_get_is_setter_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}





type Parameter_Info struct{
	h Handle
}



func (this *Parameter_Info) GetHandle() Handle{
	return this.h
}

func (this *Parameter_Info) SetHandle(h Handle){
	this.h = h
}



func (this *Parameter_Info) Get_Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = parameter_info_get_name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Parameter_Info) Get_Type_Getter() (type__ string, err error){
	

	var res []interface{}
	
	res, err = parameter_info_get_type_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Parameter_Info) Get_Is_Default_Value_Getter() (is_default_value bool, err error){
	

	var res []interface{}
	
	res, err = parameter_info_get_is_default_value_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}




func (this *Parameter_Info) Get_Is_Optional_Getter() (is_optional bool, err error){
	

	var res []interface{}
	
	res, err = parameter_info_get_is_optional_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}




func (this *Parameter_Info) Get_Kind_Getter() (kind string, err error){
	

	var res []interface{}
	
	res, err = parameter_info_get_kind_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}





type Function_Info struct{
	h Handle
}



func (this *Function_Info) GetHandle() Handle{
	return this.h
}

func (this *Function_Info) SetHandle(h Handle){
	this.h = h
}



func (this *Function_Info) Get_Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = function_info_get_name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Function_Info) Get_Comment_Getter() (comment string, err error){
	

	var res []interface{}
	
	res, err = function_info_get_comment_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Function_Info) Get_Parameters_Getter() (parameters []Parameter_Info, err error){
	

	var res []interface{}
	
	res, err = function_info_get_parameters_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]Parameter_Info), nil
}




func (this *Function_Info) Get_Return_Values_Getter() (return_values []string, err error){
	

	var res []interface{}
	
	res, err = function_info_get_return_values_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]string), nil
}





type Class_Info struct{
	h Handle
}



func (this *Class_Info) GetHandle() Handle{
	return this.h
}

func (this *Class_Info) SetHandle(h Handle){
	this.h = h
}



func (this *Class_Info) Get_Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = class_info_get_name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Class_Info) Get_Comment_Getter() (comment string, err error){
	

	var res []interface{}
	
	res, err = class_info_get_comment_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *Class_Info) Get_Fields_Getter() (fields []Variable_Info, err error){
	

	var res []interface{}
	
	res, err = class_info_get_fields_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]Variable_Info), nil
}




func (this *Class_Info) Get_Methods_Getter() (methods []Function_Info, err error){
	

	var res []interface{}
	
	res, err = class_info_get_methods_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]Function_Info), nil
}





type Py_Info struct{
	h Handle
}



func (this *Py_Info) GetHandle() Handle{
	return this.h
}

func (this *Py_Info) SetHandle(h Handle){
	this.h = h
}



func (this *Py_Info) Get_Globals_Getter() (globals []Variable_Info, err error){
	

	var res []interface{}
	
	res, err = py_info_get_globals_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]Variable_Info), nil
}




func (this *Py_Info) Get_Functions_Getter() (functions []Function_Info, err error){
	

	var res []interface{}
	
	res, err = py_info_get_functions_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]Function_Info), nil
}




func (this *Py_Info) Get_Classes_Getter() (classes []Class_Info, err error){
	

	var res []interface{}
	
	res, err = py_info_get_classes_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]Class_Info), nil
}





type Py_Extractor struct{
	h Handle
}


func NewPy_Extractor( filename string) (instance *Py_Extractor, err error){
	

	var res []interface{}
	res, err = py_extractor_py_extractor_caller( filename)
	if err != nil{
		return
	}

	inst := &Py_Extractor{
		h: res[0].(Handle),
	}
	
	return inst, nil	
}


func (this *Py_Extractor) GetHandle() Handle{
	return this.h
}

func (this *Py_Extractor) SetHandle(h Handle){
	this.h = h
}



func (this *Py_Extractor) Extract() (info Py_Info, err error){
	

	var res []interface{}
	
	res, err = py_extractor_extract_caller(this.h, )
	
	if err != nil{
		return
	}
	
	return res[0].(Py_Info), nil
}




